// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1b2grfUt-4fEGVKY2CtRr4spmdiM9yco',
    appId: '1:473478479868:web:bae6a7426dfcba10637c79',
    messagingSenderId: '473478479868',
    projectId: 'biblioteca-9395a',
    authDomain: 'biblioteca-9395a.firebaseapp.com',
    storageBucket: 'biblioteca-9395a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnw3AkNO_u9Fa7KUS87ZQwMXyfTYj6K7s',
    appId: '1:473478479868:android:38a2b8fd9d8a85f6637c79',
    messagingSenderId: '473478479868',
    projectId: 'biblioteca-9395a',
    storageBucket: 'biblioteca-9395a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHQ1vaM0QgtYFuKB0X0vv8xXb_GJgXY8',
    appId: '1:473478479868:ios:6782583694b39e3b637c79',
    messagingSenderId: '473478479868',
    projectId: 'biblioteca-9395a',
    storageBucket: 'biblioteca-9395a.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHQ1vaM0QgtYFuKB0X0vv8xXb_GJgXY8',
    appId: '1:473478479868:ios:6782583694b39e3b637c79',
    messagingSenderId: '473478479868',
    projectId: 'biblioteca-9395a',
    storageBucket: 'biblioteca-9395a.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1b2grfUt-4fEGVKY2CtRr4spmdiM9yco',
    appId: '1:473478479868:web:be04d54b52b83e73637c79',
    messagingSenderId: '473478479868',
    projectId: 'biblioteca-9395a',
    authDomain: 'biblioteca-9395a.firebaseapp.com',
    storageBucket: 'biblioteca-9395a.firebasestorage.app',
  );
}
